apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubeserver-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: youtube-server
  minReadySeconds: 6
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: youtube-server
    spec:
      containers:
      - name: youtube-server
        image: gearoidsheehan/youtube_server:latest
        ports:
        - containerPort: 50052
